/**
 * Supported languages for KathaAI
 * Each entry: native name, code (for SpeechRecognition), speechSynthesis lang code
 */
export const LANGUAGES = [
  {
    code: 'en-IN',
    name: 'English',
    nativeName: 'English',
    placeholder: 'Once upon a time, in a magical forest...',
    helloPrompt: 'What story should I tell?',
    helloSub: 'Tell me anything — a place, a feeling, a character...',
    listenBtn: '🔊 Listen to Story',
    listening: '🔊 Listening...',
    saveBtn: '💾 Save Story',
    savedBtn: '✅ Saved!',
    newStoryBtn: '🆕 New Story',
    micHint: '🎤 Tap to speak your idea, or type above',
    hapticTitle: 'Haptic Patterns in Your Story',
    hapticNote: '📳 Haptic feedback requires a supported device (Android Chrome). You can tap patterns to preview them visually.',
    sensoryTitle: 'Sensory Markers Used',
    noStories: 'No stories yet',
    noStoriesSub: 'Stories will appear here as students create them',
    createBtn: '✨ Create First Story',
  },
  {
    code: 'hi-IN',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    placeholder: 'एक समय की बात है, एक जादुई जंगल में...',
    helloPrompt: 'मैं कोई कहानी सुनाऊँ?',
    helloSub: 'कुछ भी बताओ — एक जगह, एक भावना, एक पात्र...',
    listenBtn: '🔊 कहानी सुनें',
    listening: '🔊 सुन रहे हैं...',
    saveBtn: '💾 कहानी सेव करें',
    savedBtn: '✅ सेव हो गई!',
    newStoryBtn: '🆕 नई कहानी',
    micHint: '🎤 अपनी कहानी बोलें या ऊपर टाइप करें',
    hapticTitle: 'कहानी में हैप्टिक पैटर्न',
    hapticNote: '📳 हैप्टिक फीडबैक के लिए समर्थित डिवाइस चाहिए (Android Chrome)। पैटर्न पर टैप करके प्रीव्यू देखें।',
    sensoryTitle: 'संवेदी मार्कर का उपयोग',
    noStories: 'अभी कोई कहानी नहीं',
    noStoriesSub: 'जैसे ही छात्र कहानियाँ बनाएंगे, ये यहाँ दिखेंगी',
    createBtn: '✨ पहली कहानी बनाएं',
  },
  {
    code: 'mr-IN',
    name: 'Marathi',
    nativeName: 'मराठी',
    placeholder: 'एकदा एक जादुयी जंगलात...',
    helloPrompt: 'मी काय कहाणी सांगू?',
    helloSub: 'काहीही सांगा — एक ठिकाण, एक भावना, एक पात्र...',
    listenBtn: '🔊 कहाणी ऐका',
    listening: '🔊 ऐकत आहे...',
    saveBtn: '💾 कहाणी सेव करा',
    savedBtn: '✅ सेव झाले!',
    newStoryBtn: '🆕 नवी कहाणी',
    micHint: '🎤 तुमची कहाणी सांगा किंवा वर टाईप करा',
    hapticTitle: 'कहाणीतील हॅप्टिक पॅटर्न्स',
    hapticNote: '📳 हॅप्टिक फीडबॅकसाठी समर्थित डिव्हाइस हवा (Android Chrome). पॅटर्नवर टॅप करून पहा.',
    sensoryTitle: 'संवेदी मार्कर वापर',
    noStories: 'अजून कोणतीही कहाणी नाही',
    noStoriesSub: 'विद्यार्थी कहाण्या बनवू लागल्यावर येथे दिसेल',
    createBtn: '✨ पहिली कहाणी बनवा',
  },
  {
    code: 'bn-IN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    placeholder: 'এক সময়ের কথা, এক জাদুকরী জঙ্গলে...',
    helloPrompt: 'আমি কোন গল্প বলব?',
    helloSub: 'যেকোনো কিছু বলো — একটা জায়গা, একটা অনুভূতি, একটা চরিত্র...',
    listenBtn: '🔊 গল্প শোনো',
    listening: '🔊 শোনা হচ্ছে...',
    saveBtn: '💾 গল্প সেভ করো',
    savedBtn: '✅ সেভ হয়েছে!',
    newStoryBtn: '🆕 নতুন গল্প',
    micHint: '🎤 তোমার গল্প বলো বা উপরে টাইপ করো',
    hapticTitle: 'গল্পে হ্যাপটিক প্যাটার্ন',
    hapticNote: '📳 হ্যাপটিক ফিডব্যাকের জন্য সমর্থিত ডিভাইস দরকার (Android Chrome). প্যাটার্নে ট্যাপ করে দেখো।',
    sensoryTitle: 'সংবেদী মার্কার ব্যবহার',
    noStories: 'এখনো কোনো গল্প নেই',
    noStoriesSub: 'শিক্ষার্থীরা গল্প বানালে এখানে দেখাবে',
    createBtn: '✨ প্রথম গল্প তৈরি করো',
  },
  {
    code: 'ta-IN',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    placeholder: 'ஒரு காலத்தில், ஒரு மாய காட்டில்...',
    helloPrompt: 'நான் என்ன கதை சொல்ல?',
    helloSub: 'என்னவாவது சொல் — ஒரு இடம், ஒரு உணர்வு, ஒரு கதாபாத்திரம்...',
    listenBtn: '🔊 கதை கேள்',
    listening: '🔊 கேட்கிறது...',
    saveBtn: '💾 கதை சேமி',
    savedBtn: '✅ சேமித்தது!',
    newStoryBtn: '🆕 புதிய கதை',
    micHint: '🎤 உங்கள் கதையைப் பேசுங்கள் அல்லது மேலே டைப் செய்யுங்கள்',
    hapticTitle: 'கதையில் ஹேப்டிக் பாத்றைகள்',
    hapticNote: '📳 ஹேப்டிக் ஃபீட்பேக்கிற்கு ஆதரிக்கும் சாதனம் தேவை (Android Chrome). பாத்றைகளைத் தொடவும்.',
    sensoryTitle: 'உணர்வு குறியீடுகள்',
    noStories: 'இன்னும் கதைகள் இல்லை',
    noStoriesSub: 'மாணவர்கள் கதைகள் உருவாக்கும் போது இங்கே தெரியும்',
    createBtn: '✨ முதல் கதை உருவாக்கு',
  },
  {
    code: 'te-IN',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    placeholder: 'ఒకప్పుడు, ఒక మాయ森林లో...',
    helloPrompt: 'నేను ఏ కథ చెప్పాలి?',
    helloSub: 'ఏదైనా చెప్పు — ఒక ప్రదేశం, ఒక భావన, ఒక పాత్ర...',
    listenBtn: '🔊 కథ విను',
    listening: '🔊 వింటోంది...',
    saveBtn: '💾 కథ సేవ్ చేయి',
    savedBtn: '✅ సేవ్ అయింది!',
    newStoryBtn: '🆕 కొత్త కథ',
    micHint: '🎤 మీ కథను పలికించండి లేదా పైన టైప్ చేయండి',
    hapticTitle: 'కథలో హ్యాప్టిక్ ప్యాటర్న్లు',
    hapticNote: '📳 హ్యాప్టిక్ ఫీడ్‌బ్యాక్‌కు సపోర్ట్ చేసే పరికరం అవసరం (Android Chrome). ప్యాటర్న్‌లను ట్యాప్ చేయండి.',
    sensoryTitle: 'సంవేదనా మార్కర్లు',
    noStories: 'ఇంకా కథలు లేవు',
    noStoriesSub: 'విద్యార్థులు కథలు సృష్టించినప్పుడు ఇక్కడ కనిపిస్తాయి',
    createBtn: '✨ మొదటి కథ సృష్టించు',
  },
  {
    code: 'kn-IN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    placeholder: 'ಒಂದಾವರ್ತಿ, ಒಂದು ಹೊಳಪುವ ಕಾಡಿನಲ್ಲಿ...',
    helloPrompt: 'ನಾನು ಯಾವ ಕಥೆ ಹೇಳಲಿ?',
    helloSub: 'ಎಲ್ಲವನ್ನೂ ಹೇಳಿ — ಒಂದು ಸ್ಥಳ, ಒಂದು ಭಾವನೆ, ಒಂದು ಪಾತ್ರ...',
    listenBtn: '🔊 ಕಥೆ ಕೇಳಿ',
    listening: '🔊 ಕೇಳುತ್ತಿದೆ...',
    saveBtn: '💾 ಕಥೆ ಸೇವ್ ಮಾಡಿ',
    savedBtn: '✅ ಸೇವ್ ಆಯಿತು!',
    newStoryBtn: '🆕 ಹೊಸ ಕಥೆ',
    micHint: '🎤 ನಿಮ್ಮ ಕಥೆ ಹೇಳಿ ಅಥವಾ ಮೇಲೆ ಟೈಪ್ ಮಾಡಿ',
    hapticTitle: 'ಕಥೆಯಲ್ಲಿ ಹ್ಯಾಪ್ಟಿಕ್ ಪ್ಯಾಟರ್ನ್‌ಗಳು',
    hapticNote: '📳 ಹ್ಯಾಪ್ಟಿಕ್ ಫೀಡ್‌ಬ್ಯಾಕ್‌ಗೆ ಬೆಂಬಲಿತ ಸಾಧನ ಬೇಕು (Android Chrome). ಪ್ಯಾಟರ್ನ್‌ಗಳನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.',
    sensoryTitle: 'ಸಂವೇದನಾ ಮಾರ್ಕರ್‌ಗಳು',
    noStories: 'ಇನ್ನೂ ಕಥೆಗಳಿಲ್ಲ',
    noStoriesSub: 'ವಿದ್ಯಾರ್ಥಿಗಳು ಕಥೆಗಳನ್ನು ರಚಿಸಿದಾಗ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ',
    createBtn: '✨ ಮೊದಲ ಕಥೆ ರಚಿಸಿ',
  },
  {
    code: 'ml-IN',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    placeholder: 'ഒരിക്കൽ, ഒരു മാന്ത്രിക വനത്തിൽ...',
    helloPrompt: 'ഞാൻ എന്ത് കഥ പറയട്ടെ?',
    helloSub: 'എന്തെങ്കിലും പറയൂ — ഒരു സ്ഥലം, ഒരു ഉണർവ്, ഒരു കഥാപാത്രം...',
    listenBtn: '🔊 കഥ കേൾക്കുക',
    listening: '🔊 കേൾക്കുന്നു...',
    saveBtn: '💾 കഥ സേവ് ചെയ്യുക',
    savedBtn: '✅ സേവ് ചെയ്തു!',
    newStoryBtn: '🆕 പുതിയ കഥ',
    micHint: '🎤 നിങ്ങളുടെ കഥ പറയുക അല്ലെങ്കിൽ മുകളിൽ ടൈപ്പ് ചെയ്യുക',
    hapticTitle: 'കഥയിലെ ഹാപ്റ്റിക് പാറ്റേണുകൾ',
    hapticNote: '📳 ഹാപ്റ്റിക് ഫീഡ്‌ബാക്ക്‌ക്ക് സപ്പോർട്ടുള്ള ഉപകരണം വേണം (Android Chrome). പാറ്റേണുകളിൽ ടാപ്പ് ചെയ്യുക.',
    sensoryTitle: 'സംവേദന മാർക്കറുകൾ',
    noStories: 'ഇതുവരെ കഥകളില്ല',
    noStoriesSub: 'വಿದ്യാര্থികൾ കഥകൾ സൃഷ്ടിക്കുമ്പോൾ ഇവിടെ കാണാം',
    createBtn: '✨ ആദ്യ കഥ സൃഷ്ടിക്കുക',
  },
  {
    code: 'gu-IN',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    placeholder: 'એક વખતની વાત, એક જાદુઈ જંગલમાં...',
    helloPrompt: 'હું કેવો વાર્તા કહાઉં?',
    helloSub: 'શું પણ કહો — એક જગ્યા, એક ભાવના, એક પાત્ર...',
    listenBtn: '🔊 વાર્તા સાંભળો',
    listening: '🔊 સાંભળી રહ્યા છીએ...',
    saveBtn: '💾 વાર્તા સેવ કરો',
    savedBtn: '✅ સેવ થઈ!',
    newStoryBtn: '🆕 નવી વાર્તા',
    micHint: '🎤 તમારી વાર્તા બોલો અથવા ઉપર ટાઈપ કરો',
    hapticTitle: 'વાર્તામાં હેપ્ટિક પેટર્ન',
    hapticNote: '📳 હેપ્ટિક ફીડબેક માટે સપોર્ટેડ ડિવાઇસ જોઈએ (Android Chrome). પેટર્ન પર ટેપ કરો.',
    sensoryTitle: 'સંવેદી માર્કર્સ',
    noStories: 'હજુ કોઈ વાર્તા નથી',
    noStoriesSub: 'છાત્રો વાર્તાઓ બનાવે ત્યારે અહીં દેખાશે',
    createBtn: '✨ પ્રથમ વાર્તા બનાવો',
  },
  {
    code: 'pa-IN',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    placeholder: 'ਇੱਕ ਵਾਰ ਦੀ ਗੱਲ ਹੈ, ਇੱਕ ਜਾਦੂਈ ਜੰਗਲ ਵਿੱਚ...',
    helloPrompt: 'ਮੈਂ ਕਿਹੜੀ ਕਹਾਣੀ ਸੁਣਾਉਂ?',
    helloSub: 'ਕੁਝ ਵੀ ਬਤਾਓ — ਇੱਕ ਥਾਂ, ਇੱਕ ਭਾਵਨਾ, ਇੱਕ ਕਿਰਦਾਰ...',
    listenBtn: '🔊 ਕਹਾਣੀ ਸੁਣੋ',
    listening: '🔊 ਸੁਣ ਰਿਹਾ ਹੈ...',
    saveBtn: '💾 ਕਹਾਣੀ ਸੇਵ ਕਰੋ',
    savedBtn: '✅ ਸੇਵ ਹੋ ਗਈ!',
    newStoryBtn: '🆕 ਨਵੀਂ ਕਹਾਣੀ',
    micHint: '🎤 ਆਪਣੀ ਕਹਾਣੀ ਬੋਲੋ ਜਾਂ ਉੱਪਰ ਟਾਈਪ ਕਰੋ',
    hapticTitle: 'ਕਹਾਣੀ ਵਿੱਚ ਹੈਪਟਿਕ ਪੈਟਰਨ',
    hapticNote: '📳 ਹੈਪਟਿਕ ਫੀਡਬੈਕ ਲਈ ਸਮਰੱਥ ਡਿਵਾਈਸ ਚਾਹੀਦੀ ਹੈ (Android Chrome)। ਪੈਟਰਨ ਤੇ ਟੈਪ ਕਰੋ।',
    sensoryTitle: 'ਸੰਵੇਦੀ ਮਾਰਕਰ',
    noStories: 'ਹੁਣ ਤੱਕ ਕੋਈ ਕਹਾਣੀ ਨਹੀਂ',
    noStoriesSub: 'ਜਦੋਂ ਵਿਦਿਆਰਥੀ ਕਹਾਣੀਆਂ ਬਣਾਉਣਗੇ ਤਾਂ ਇੱਥੇ ਦਿਖੇਗੀ',
    createBtn: '✨ ਪਹਿਲੀ ਕਹਾਣੀ ਬਣਾਓ',
  },
  {
    code: 'or-IN',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    placeholder: 'ଏକ ସମୟର କଥା, ଏକ ମାୟାବୀ ଜଙ୍ଗଲରେ...',
    helloPrompt: 'ମୁଁ କେଉଁ କାହାଣୀ କହିବି?',
    helloSub: 'କିଛି କୁହ — ଏକ ଠାଏ, ଏକ ଅନୁଭୂତି, ଏକ ଚରିତ୍ର...',
    listenBtn: '🔊 କାହାଣୀ ଶୁଣ',
    listening: '🔊 ଶୁଣୁଛି...',
    saveBtn: '💾 କାହାଣୀ ସେଭ୍ କର',
    savedBtn: '✅ ସେଭ୍ ହୋଇଛି!',
    newStoryBtn: '🆕 ନୂତନ କାହାଣୀ',
    micHint: '🎤 ଆପଣଙ୍କ କାହାଣୀ କୁହନ୍ତୁ କିମ୍ବା ଉପରେ ଟାଇପ୍ କରନ୍ତୁ',
    hapticTitle: 'କାହାଣୀରେ ହ୍ୟାପ୍ଟିକ୍ ଧାଡ଼ି',
    hapticNote: '📳 ହ୍ୟାପ୍ଟିକ୍ ଫିଡବ୍ୟାକ୍ ପାଇଁ ସମର୍ଥନୀୟ ଡିଭାଇସ୍ ଦରକାର (Android Chrome)। ଧାଡ଼ି ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ।',
    sensoryTitle: 'ସଂବେଦୀ ମାର୍କର',
    noStories: 'ଏବେ ପର୍ଯ୍ୟନ୍ତ କୌଣସି କାହାଣୀ ନାହିଁ',
    noStoriesSub: 'ଛାତ୍ରମାନେ କାହାଣୀ ତିଆରି କଲେ ଏଠାରେ ଦେଖାଯିବ',
    createBtn: '✨ ପ୍ରଥମ କାହାଣୀ ତିଆରି କରନ୍ତୁ',
  },
  {
    code: 'ur-IN',
    name: 'Urdu',
    nativeName: 'اردو',
    placeholder: 'ایک وقت کی بات ہے، ایک جادوئی جنگل میں...',
    helloPrompt: 'میں کیا کہانی سنائوں؟',
    helloSub: 'کچھ بھی بتاؤ — ایک جگہ، ایک احساس، ایک کردار...',
    listenBtn: '🔊 کہانی سنو',
    listening: '🔊 سن رہا ہے...',
    saveBtn: '💾 کہانی محفوظ کرو',
    savedBtn: '✅ محفوظ ہوئی!',
    newStoryBtn: '🆕 نئی کہانی',
    micHint: '🎤 اپنی کہانی بولو یا اوپر ٹائپ کرو',
    hapticTitle: 'کہانی میں ہاپٹک پیٹرن',
    hapticNote: '📳 ہاپٹک فیڈبیک کے لیے سپورٹڈ ڈیوائس چاہیے (Android Chrome)۔ پیٹرن پر ٹیپ کرو۔',
    sensoryTitle: 'حسی نشانیاں',
    noStories: 'ابھی کوئی کہانی نہیں',
    noStoriesSub: 'جب طلباء کہانیاں بنائیں گے تو یہاں نظر آئیں گی',
    createBtn: '✨ پہلی کہانی بنائیں',
  },
  {
    code: 'as-IN',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    placeholder: 'এক সময়ৰ কথা, এটা জাদুকৰী জংগলত...',
    helloPrompt: 'মই কিয়দৰে কथा কওঁ?',
    helloSub: 'কেতিয়াও কওক — এটা ঠাই, এটা অনুভূতি, এটা চৰিত্ৰ...',
    listenBtn: '🔊 কथा শুনক',
    listening: '🔊 শুনি আছে...',
    saveBtn: '💾 কथा সংৰক্ষণ কৰক',
    savedBtn: '✅ সংৰক্ষণ হৈছে!',
    newStoryBtn: '🆕 নতুন কথা',
    micHint: '🎤 আপোনাৰ কথা কওক অথবা ওপৰত টাইপ কৰক',
    hapticTitle: 'কথাত হেপ্টিক প্যাটাৰ্ন',
    hapticNote: '📳 হেপ্টিক ফীডবেকেৰে বাবে সমৰ্থিত ডিভাইচ দৰকাৰ (Android Chrome)। প্যাটাৰ্নত টেপ কৰক।',
    sensoryTitle: 'সংবেদী মাৰ্কাৰ',
    noStories: 'এতিয়ালৈকে কোনো কথা নাই',
    noStoriesSub: 'ছাত্ৰ-ছাত্ৰীসকলে কথা সৃষ্টি কৰিলে ইয়াত দেখা যাব',
    createBtn: '✨ প্ৰথম কথা সৃষ্টি কৰক',
  },
  {
    code: 'ma-IN',
    name: 'Maithili',
    nativeName: 'मैथिली',
    placeholder: 'एक समयाक बात, एगो जादुई जंगलमे...',
    helloPrompt: 'म किछु कहानी सुनाऊ?',
    helloSub: 'कुनो भी बतउ — एगो ठाम, एगो भावना, एगो पात्र...',
    listenBtn: '🔊 कहानी सुनू',
    listening: '🔊 सुनि रहल छी...',
    saveBtn: '💾 कहानी सेव कराउ',
    savedBtn: '✅ सेव भऽ गेल!',
    newStoryBtn: '🆕 नव कहानी',
    micHint: '🎤 अपने कहानी बोलू अथवा उपर टाइप करू',
    hapticTitle: 'कहानीमे हैप्टिक पैटर्न',
    hapticNote: '📳 हैप्टिक फीडबैकक लेल समर्थित डिभाइस चाही। पैटर्न पर टैप करू।',
    sensoryTitle: 'संवैदिक मार्कर',
    noStories: 'हिने कोनो कहानी नहि',
    noStoriesSub: 'जख विद्यार्थी कहानी बनाबलै तखन ईथि दिखत',
    createBtn: '✨ पहिली कहानी बनाउ',
  },
]

/**
 * Get language object by code
 */
export function getLanguage(code) {
  return LANGUAGES.find((l) => l.code === code) || LANGUAGES[0]
}

/**
 * Get all codes for SpeechRecognition
 */
export const SPEECH_LANGUAGES = LANGUAGES.map((l) => l.code)

/**
 * Map language code to Gemini system prompt instruction
 */
export const LANGUAGE_INSTRUCTIONS = {
  'en-IN': 'Write the story entirely in English.',
  'hi-IN': 'Write the story entirely in Hindi (हिन्दी) using Devanagari script. Use simple, child-friendly Hindi.',
  'mr-IN': 'Write the story entirely in Marathi (मराठी) using Devanagari script. Use simple, child-friendly Marathi.',
  'bn-IN': 'Write the story entirely in Bengali (বাংলা) using Bengali script. Use simple, child-friendly Bengali.',
  'ta-IN': 'Write the story entirely in Tamil (தமிழ்) using Tamil script. Use simple, child-friendly Tamil.',
  'te-IN': 'Write the story entirely in Telugu (తెలుగు) using Telugu script. Use simple, child-friendly Telugu.',
  'kn-IN': 'Write the story entirely in Kannada (ಕನ್ನಡ) using Kannada script. Use simple, child-friendly Kannada.',
  'ml-IN': 'Write the story entirely in Malayalam (മലയാളം) using Malayalam script. Use simple, child-friendly Malayalam.',
  'gu-IN': 'Write the story entirely in Gujarati (ગુજરાતી) using Gujarati script. Use simple, child-friendly Gujarati.',
  'pa-IN': 'Write the story entirely in Punjabi (ਪੰਜਾਬੀ) using Gurmukhi script. Use simple, child-friendly Punjabi.',
  'or-IN': 'Write the story entirely in Odia (ଓଡ଼ିଆ) using Odia script. Use simple, child-friendly Odia.',
  'ur-IN': 'Write the story entirely in Urdu (اردو) using Nastaliq script. Use simple, child-friendly Urdu.',
  'as-IN': 'Write the story entirely in Assamese (অসমীয়া) using Bengali-Assamese script. Use simple, child-friendly Assamese.',
  'ma-IN': 'Write the story entirely in Maithili (मैथिली) using Devanagari script. Use simple, child-friendly Maithili.',
}
